[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.5.2"

#- https://dev.to/ender_minyard/rust-nostd-template-23j0
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
